<?php

return [
    // The Telegram BOT api token (default)
    'token' => env('TELEGRAM_BOT_TOKEN'),
    'log_channel' => env('TELEGRAM_BOT_LOG_CHANNEL', 'null'),

    // The Telegram BOT api token (Armenia)
    'token_armenia' => env('TELEGRAM_BOT_TOKEN_ARMENIA'),
    'username_armenia' => env('TELEGRAM_BOT_USERNAME_ARMENIA'),
    'log_channel_armenia' => env('TELEGRAM_BOT_LOG_CHANNEL_ARMENIA', 'null'),
    'channel_token_armenia' => env('TELEGRAM_BOT_CHANNEL_TOKEN_ARMENIA'),
    'channel_log_channel_armenia' => env('TELEGRAM_BOT_CHANNEL_LOG_CHANNEL_ARMENIA', 'null'),
    'listing_armenia_channel_id' => env('TELEGRAM_LISTING_ARMENIA_CHANNEL_ID'),
    'event_armenia_channel_id' => env('TELEGRAM_EVENT_ARMENIA_CHANNEL_ID'),

    // The Telegram BOT api token (Georgia)
    'token_georgia' => env('TELEGRAM_BOT_TOKEN_GEORGIA'),
    'username_georgia' => env('TELEGRAM_BOT_USERNAME_GEORGIA'),
    'log_channel_georgia' => env('TELEGRAM_BOT_LOG_CHANNEL_GEORGIA', 'null'),
    'channel_token_georgia' => env('TELEGRAM_BOT_CHANNEL_TOKEN_GEORGIA'),
    'channel_log_channel_georgia' => env('TELEGRAM_BOT_CHANNEL_LOG_CHANNEL_GEORGIA', 'null'),
    'listing_georgia_channel_id' => env('TELEGRAM_LISTING_GEORGIA_CHANNEL_ID'),
    'event_georgia_channel_id' => env('TELEGRAM_EVENT_GEORGIA_CHANNEL_ID'),

    // The Telegram BOT api token (Thailand)
    'token_thailand' => env('TELEGRAM_BOT_TOKEN_THAILAND'),
    'username_thailand' => env('TELEGRAM_BOT_USERNAME_THAILAND'),
    'log_channel_thailand' => env('TELEGRAM_BOT_LOG_CHANNEL_THAILAND', 'null'),
    'channel_token_thailand' => env('TELEGRAM_BOT_CHANNEL_TOKEN_THAILAND'),
    'channel_log_channel_thailand' => env('TELEGRAM_BOT_CHANNEL_LOG_CHANNEL_THAILAND', 'null'),
    'listing_thailand_channel_id' => env('TELEGRAM_LISTING_THAILAND_CHANNEL_ID'),
    'event_thailand_channel_id' => env('TELEGRAM_EVENT_THAILAND_CHANNEL_ID'),

    // The Telegram BOT api token (Turkey)
    'token_turkey' => env('TELEGRAM_BOT_TOKEN_TURKEY'),
    'username_turkey' => env('TELEGRAM_BOT_USERNAME_TURKEY'),
    'log_channel_turkey' => env('TELEGRAM_BOT_LOG_CHANNEL_TURKEY', 'null'),
    'channel_token_turkey' => env('TELEGRAM_BOT_CHANNEL_TOKEN_TURKEY'),
    'channel_log_channel_turkey' => env('TELEGRAM_BOT_CHANNEL_LOG_CHANNEL_TURKEY', 'null'),
    'listing_turkey_channel_id' => env('TELEGRAM_LISTING_TURKEY_CHANNEL_ID'),
    'event_turkey_channel_id' => env('TELEGRAM_EVENT_TURKEY_CHANNEL_ID'),

    // The Telegram BOT api secret
    'secret' => env('TELEGRAM_BOT_SECRET'),

    // if the webhook mode must validate the incoming IP range is from a telegram server
    'safe_mode' => env('APP_ENV', 'local') === 'production',

    // Extra or specific configurations
    'config' => [],

    // Set if the service provider should automatically load
    // handlers from /routes/telegram.php
    'routes' => false,

    // Enable or disable Nutgram mixins
    'mixins' => false,

    // Path to save files generated by nutgram:make command
    'namespace' => app_path('Telegram'),

    // The path to store temporary files relative to the "storage/app" folder.
    'tmp_folder' => "telegram-tmp",
];
